### ISSUE TITLE
"Column" setting does not take effect before VS Code restart

### ISSUE THREAD

**Issue by wgslr** [tchayen/markdown-links#1]
Steps to reproduce (assuming starting with the value "active"):

1. Open a markdown file
2. ctrl+ship+p -> Show Graph
3. Observe the graph shown in the current column
4. Close the graph tab
5. Change the setting to "two"
6. ctrl+ship+p -> Show Graph
7. Observe the graph still shown in the current column
8. Restart VS Code
9. ctrl+ship+p -> Show Graph
10. Observe the graph correctly shown in column two

**Comment by tchayen** [comment]
Thanks for reporting the issue!

Apparently it looks like it wasn't working at all. I separated it into two separate settings: `showColumn` and `openColumn`. First one determines where extension's webview will show, second where the files opened with it will appear. This should be more useful.

Changes described above are live on `master` and in `0.3.0` version in the marketplace.
