### ISSUE TITLE
Add extensions into open-vsx

### ISSUE THREAD

**Issue by madeindjs** [tchayen/markdown-links#11]
Currently this extension is not availbale for [VSCodium](https://github.com/VSCodium/vscodium). To correct that, you just need to [follow this guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by tchayen** [comment]
I was not aware such thing existed. I will definitely look into it. Thanks a lot!

**Comment by tchayen** [comment]
Just published the `0.7.0` to vscodium (and some friendly soul published 0.6.0 before) so we can consider it done 🥳.
