### ISSUE TITLE
New documents don't automatically get added to the graph

### ISSUE THREAD

**Issue by jevakallio** [tchayen/markdown-links#12]
Loving your work on this extension! 

It would be cool if a new document could get added to the graph automatically.

Consider a use case:

1. I am writing a document while the graph is open
2. I want to create a new document, called LInk 
3. I type `[Link](link.md)`inthe current document and create the file in the directory (possibly via an automation)
4. I give the new file a `# Heading`

Expected outcome: New document "Link: shows up in the graph.

This is definitely a nice to have, just logging it here.

**Comment by tchayen** [comment]
Sorry for late response.

I believe that I implemented a mechanism for watching files in the workspace and what you've described exactly matches the intended behavior. I will have another look what can cause problems with it.
