### ISSUE TITLE
Extension not adding new command

### ISSUE THREAD

**Issue by ziofil** [tchayen/markdown-links#15]
After installing the extension in VScode, the command `show graph` is not available. Am I doing it wrong?

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by tchayen** [comment]
Are you typing `⇧⌘P` and the look for the command there? Maybe there was some misunderstanding what command means.
