### ISSUE TITLE
Toggle Folder(s) to view in the graph

### ISSUE THREAD

**Issue by sahil48** [tchayen/markdown-links#16]
In reference to https://github.com/foambubble/foam/issues/5

@tchayen @jevakallio

The ideas I had in mind for the implementation are below.

I would like to specify folders that Markdown-Links searches in the settings.

Once the folders are selected, by default, the graph shows the relationship between all files in the identified folders. When a file is open, an option in the graph should be available to:

1 Show links from all folders
2 Show links from current folder only
3 Show links from current folder and its subfolders
4 Memorize graph
5 Show memorized graph

The graph will keep changing dynamically in options 2 and 3 to reflect the folder of the active file and focus on the active file.

**Comment by jevakallio** [comment]
This sounds interesting, but perhaps not the most user-friendly approach. @sahil48 could you describe the problem you are solving, or a real use case for a functionality like this, and perhaps we could design an approach that could solve it while remaining simple to use

**Comment by tchayen** [comment]
I started thinking about it and here are my further thoughts:

- Why should folders for searching be specified in settings? Running things in context of open workspace is a very common convention and even though putting it in settings would work, I believe it would be rather misleading for most users.
- 2: what do you mean by current folder only? Is it workspace?
- 4: what would memorization be for? Do you find it to be a performance problem?

Again, I think that in this form, the idea is not compatible with what I perceive as typical usage of vscode or common behaviour of a vscode extension (which of course may vary and is very individual thing).

If you wish we can iterate on a possible solution but as @jevakallio pointed, I'd like to ask what problem exactly do you want to solve?

**Comment by sahil48** [comment]
@jevakallio @tchayen 

Apologies for the delay in response. It took me a while to think through this. I think you are largely right that the ideas below may not be compatible with the markdown-links extension itself.

markdown-links currently presents an extremely dynamic view of files and there relationships as new files get created, updated, and mentioned by other files. This is an appropriate default and works fantastically as an exploratory tool, but the dynamism has disadvantages for using is as a form of navigation. There is value in muscle memory. Folders in the file-system are easier to navigate because the location of things do not change frequently and if you need to go to a specific file, you always click through the same sequence of folders.

A lot of the features I was suggesting were not so much out of a performance concern, but moreso to establish some static views or parts of the graph that a user would want to access over and over again as a starting point or a subset of files to be graphed to explore to enable the extension to work more as a research tool rather than a purely exploratory tool where you always have to think when reviewing what topics are available from the current file open. Additionally, some way to lock on a specific file and show the series of relationships that go from the locked file to the active file. This second type of view could help in finding supplemental information for understanding the relationships between two files better, and help foam in progressing from a personal knowledge management tool to secondarily assisting individuals collaborating on a foam workspace and consolidating the research that have been entered by multiple individuals in the workspace.

I don't have a good idea on how best to do this. One other idea I had in mind was a search tool built into the extension with ability to save search keywords, and a toggle for the number of levels of relationships to show for honing in on a given subject in the graph, but there are a lot of ways to go about this.

**Comment by tchayen** [comment]
Thank you for the answers and your thoughts!

I like those ideas but they would add a lot of complexity to Markdown Links and I am not sure if this is the right way to go. I prefer to focus on stability and bug fixes in the coming weeks but I definitely want to explore ideas like this later on.

I am once again thankful for your ideas and closing the issue for now since I won't be able to start working on it now.
