### ISSUE TITLE
Links/references with encoded spaces are not working

### ISSUE THREAD

**Issue by dynobo** [tchayen/markdown-links#18]
Hi, 

if I reference a file using the long/default markdown syntax (eg. `[My Link Text](./FileName.md)` to reference `FileName.md`), the file will be discovered and shown correctly in the graph.

However, if I reference a file with a space in the filename, it's common practice to encode the space with `%20`, like `[My Link Text](./File%20Name.md)` for for `File Name.md`. However, those links are not discovered by markdown-links and are therefore not shown in the graph. 

Any possibility to fix this?

PS: Thanks for the nice extension! :-)

**Comment by tchayen** [comment]
Absolutely. Decoding the url sounds like a very reasonable things to do. I will try to add it soon.

**Comment by vanadium23** [comment]
Have encountered same issue today.
I think we can simple fix it after #35 will be merged.

**Comment by Cabeda** [comment]
Hi! Need any help with this?

**Comment by Cabeda** [comment]
@tchayen could you take a look at this PR https://github.com/tchayen/markdown-links/pull/70? I think it solves the issue

**Comment by tchayen** [comment]
@Cabeda sure, I will check it today.

**Comment by tchayen** [comment]
Fixed in #70
