### ISSUE TITLE
Support for alternative extensions

### ISSUE THREAD

**Issue by akzaidi** [tchayen/markdown-links#19]
I often utilize [rmarkdown](https://rmarkdown.rstudio.com/) formatted documents. Would it be possible to include these as links in the graph view, perhaps through a settings parameter? 

The following setting gets markdown preview to work along with backlinks in [vscode-markdown-notes](https://github.com/kortina/vscode-markdown-notes), but doesn't seem to work for the graph view in the markdown-links extension:

```json
  "files.associations": {
    "*.rmd": "markdown"
  },
```

**Comment by tchayen** [comment]
It was hardcoded in the code but it absolutely makes sense to support it properly. Adding to the TODO list.

Thanks for reporting it!

**Comment by thomaskoppelaar** [comment]
+1 On this: I'd love support for .mdx files myself.
