### ISSUE TITLE
Support for declaring title in frontmatter?

### ISSUE THREAD

**Issue by benrobertsonio** [tchayen/markdown-links#22]
I have an existing set of notes where I have my page titles defined in frontmatter (the notes are used in [gatsby-theme-brain](https://github.com/aengusmcmillin/gatsby-theme-brain)), like this:

```
---
title: Drafts
aliases: ["drafts"]
---
```

Would you be open to a PR that checks the frontmatter for a title, but falls back to the first h1 if not found?

**Comment by kevinslin** [comment]
all my notes have titles in the frontmatter. would be happy to work on this as well. maybe make it an optional configuration?

**Comment by tchayen** [comment]
Hi!

I think what you describe should be ok for the majority of users. I'll be happy to accept a PR with the change you mentioned, even better with a setting to turn it on/off (not sure which one should be the default though).

I will also try to do it myself as soon as I find time but unfortunately it might take several days.

Thanks again!

**Comment by tchayen** [comment]
I have created a common issue for all feature requests regarding title discovery and linking systems. See #28 for the progress.
