### ISSUE TITLE
Option to create node-map from filenames

### ISSUE THREAD

**Issue by sahil48** [tchayen/markdown-links#24]
I don’t like to have all files I want to add in the graph have the first heading the same as the title, especially longer documents, or documents I would want to publish as or send by copying and pasting it (Ex. Emails). It would be great if an option was available to select between using the file names for generating the graph and first level heading for generating the graph

**Comment by tchayen** [comment]
Yeah. It would be better to have it as an option. I am also considering fallback to file name in case when the title is missing, but it is hard to judge what would work better.

**Comment by sahil48** [comment]
Falling back to file name in case title is missing or there is a conflict between two headings sounds like a good idea to me. When there is a conflict in the file name, using the next folder up (relative path) until the conflict is resolved could work very well.

This is an approach taken by the extension vscode-memo (https://github.com/svsool/vscode-memo)

![image](https://user-images.githubusercontent.com/6100774/87305107-f083a100-c4e3-11ea-8a7d-52ff918f3d09.png)

**Comment by tchayen** [comment]
Hm, this also requires a global registry of file names but IIRC we have sth similar in place since it was needed for Zettlr style links. I am adding it to TODO.

**Comment by sahil48** [comment]
Okay. I wanted to detail some other syntax ideas here for explicitly referring to a heading or filename. Accidentally put in in a foam issue before I realized I was mixing two issues together. 🤦‍♂️ 

Suppose you had a file FileName1.md with heading # Heading1. You use [[Heading1]] to link via the first heading and [[FileName1.md]] to refer to the file name itself. If there is a conflict add the parent folder [[ParentFolderTitle/FileName1.md]]. Same for headings [[FileName1.md/Heading 1]]. As a side benefit, you can link to a pdf or word file and include it in the map [[ExternalFile.pdf]] that can open the pdf with an external application viewer when clicked.

**Comment by tchayen** [comment]
Ok, it sounds like another extension to the linking syntax.

As there are many popular competing non-standard systems, I am currently planning to refactor code and make it easier to add many optional alternatives to linking files. I don't think I will be doing it myself, but you will be able to contribute your idea as another option.

Thanks for your feedback! I am closing the issue now, but the topic will for sure come back once proper support for custom linking is ready.
