### ISSUE TITLE
[idea] exclude files listed in .gitignore

### ISSUE THREAD

**Issue by absurdist** [tchayen/markdown-links#25]

**Comment by tchayen** [comment]
Why would you add Markdown files to `.gitignore`?

**Comment by ianjsikes** [comment]
I have a usecase. The graphs are picking up README.md files from my node_modules directory, which generates a bunch of annoying floating nodes in the graph.

**Comment by tchayen** [comment]
It was discussed somewhere else that it would be cool to have a configuration option for disabling some files/directories, but now when I think about it, it makes a lot sense to consider `.gitignore` too. I will definitely add this when working on that one.

Thanks for reporting!

**Comment by absurdist** [comment]
Hello tchayen, ianjsikes has actually come back with the exact use case that motivated me to make the suggestion. Thanks for considering the idea.
