### ISSUE TITLE
[idea] add support for [title](file) syntax

### ISSUE THREAD

**Issue by absurdist** [tchayen/markdown-links#26]
eg.

```
[Horizontal genetic transfer](horizontal-genetic-transfer.md) 
```

**Comment by absurdist** [comment]
oh just realised that you do support this syntax, it's just not working for me, I'll investigate further...

**Comment by absurdist** [comment]
Only link type A is being included in the graph for me in visual studio 1.47.0
```

A
[[systematics]]

B
inline [systematics](systematics.md) 

C
[alternate](systematics.md)

D
[systematics]

REF

[systematics]: systematics.md

```

**Comment by star191** [comment]
same problem :(
The examples from `markdown-links\examples\functionality` don't work
Only `wiki-links` with `[[file1.md]]`

**Comment by tchayen** [comment]
This is strange. What operating system @absurdist @star191 do you use?

Those kind of links definitely work for me and were working since the beginning.

**Comment by darrensapalo** [comment]
Hi. Same thing happens to me, and can confirm, links only show up for case A as described above.

My environment is Visual Studio Code (1.46.1) and Windows 10 Enterprise 1909.

**Comment by absurdist** [comment]
i'm on windows 10 pro 10.0.18363 vscode 1.47.0. I'll come back to this and try get set up so I can debug next weekend.
Thanks for the great project

**Comment by star191** [comment]
> This is strange. What operating system @absurdist @star191 do you use?
> 
> Those kind of links definitely work for me and were working since the beginning.

Windows 10, 
VSCodium 1.47.0 - not works
VSCode 1.47.0 - not works too

**Comment by star191** [comment]
> (Fantastic project, by the way)

Yeah, true

**Comment by tchayen** [comment]
Ok, so looks like Windows is most likely the common cause here. I am able to debug it there so I will try to at least have a look today and hopefully fix it.

Thanks for reporting the problem and for your support! I will try to do my best fixing it ASAP.

**Comment by ingalless** [comment]
@tchayen Hopefully, #35 resolves this. Appreciate it may be a little out of scope of the PR, but it was in scope in the code 😛

**Comment by wjsetzer** [comment]
Is the linked PR going into the next release or an upcoming patch? It would be great to have this fix on Windows.

**Comment by tchayen** [comment]
Sorry for making you wait. I will soon release a patch with the fix
