### ISSUE TITLE
Support for links with spaces and mixed case

### ISSUE THREAD

**Issue by michaelmior** [tchayen/markdown-links#27]
VS Code correctly links `[[foo bar]]`  to `foo-bar.md` but this isn't currently detected  by the graph or properly rendered in the produced HTML. Similarly, `Foo` correctly links to `foo.md`, but this link isn't detected either.

**Comment by wgslr** [comment]
Hi! Let's unpack o few things here:

> VS Code correctly links [[foo bar]] to foo-bar.md
1. This isn't the behaviour of vanilla VS Code, but rather the [Markdown Notes](https://github.com/kortina/vscode-markdown-notes) extension, which is not associated with markdown-links (although they are both included in [Foam](url))
2. The matter of compatible file name handling between those two extensions is already being discussed in PR #21 

> or properly rendered in the produced HTML

This is way out of scope for this extension, markdown rendering is handled by VS Code itself.

> Similarly, Foo correctly links to foo.md

Do you mean `Foo` by itself, or `[[Foo]]`? I would be very surprised if it was the former!

**Comment by tchayen** [comment]
Adding to what @wgslr said:

`[[This kind of link]]` is not a part of any Markdown standard. It is just a convention used in various wiki/note oriented tools that also happens to be supported in most of them.

I hope to eventually support all popular linking systems for Markdown files. Currently we do support:
- proper markdown links: `[link](filename.md)`
- references `[link] ... [link]: filename.md`
- Zettlr-style links where `[link]` is matched elsewhere by configured regular expression
- most likely I forgot something else

And as soon as we settle on some solution in #21 we will begin to support the way you are describing here. It will take some time though, as we have to make sure those non-standard systems won't start breaking each other.

Thanks for reporting the problem!

**Comment by michaelmior** [comment]
I meant `[[Foo]]`, not `Foo` :)
