### ISSUE TITLE
[Idea] More concise diagram

### ISSUE THREAD

**Issue by MrHeer** [tchayen/markdown-links#36]
I hope there is another display mode, with the current document as the center, the left side represents those files that reference the current file, and the right represents those files referenced by the current file.

Like this:[mindmap](https://g6.antv.vision/en/examples/tree/mindmap)
![Screen Shot 2020-07-24 at 16 25 26](https://user-images.githubusercontent.com/18595761/88373372-51578700-cdca-11ea-9e54-206917b7055a.png)

**Comment by tchayen** [comment]
Thanks a lot for bringing this up!

I agree that we could benefit from having some other methods of displaying the graph, but it would require a lot of work – adding various rendering methods, making sure the graph is abstract enough to provide data to them, handling some additional constraints (for example what you mention is a tree-based layout which would require various conditions to be met – see [here](https://techdifferences.com/difference-between-tree-and-graph.html)).

So: yes, we are most likely heading in direction that will at some point support more visualisation formats but unfortunately it won't happen anytime soon as I don't think we are ready for that kind of a jump yet.
