### ISSUE TITLE
Adding new links creates a temporary duplication of the node that was linked from

### ISSUE THREAD

**Issue by nixsee** [tchayen/markdown-links#39]
Here's a screen recording of the issue. You can see that "test-page" gets duplicated and the graph gets really bizarre. I have to close and re-open the graph for it to work again. (zoom in to get rid of the odd grid that is showing)

![markdownlinks](https://user-images.githubusercontent.com/24255237/88486102-8e418c00-cf38-11ea-8638-950c60f40a8e.gif)

**Comment by tchayen** [comment]
Either already fixed (or I was fast to talk about releasing but too lazy to actually do it, as usual) or soon. Closing!
