### ISSUE TITLE
Graph not showing in GistPad

### ISSUE THREAD

**Issue by mukhtharcm** [tchayen/markdown-links#42]
When viewing files from my [Foam ](https://github.com/foambubble/foam)workspace using **[Gistpad](https://github.com/vsls-contrib/gistpad)**, I am ubable to view the graph.
It is showing,
![image](https://user-images.githubusercontent.com/56378562/88635211-093fa980-d0d5-11ea-8f4c-1c10091ff7ce.png)

Is there any workaround for this?

**Comment by tchayen** [comment]
I would have to look deeper into it if there's an easy workaround or if I am missing something, but basically the whole graph is based around the idea of working on the open workspace so it might be tricky to change.

**Comment by mukhtharcm** [comment]
Then gistpad isn't an actual workspace?
I don't know, I am a noob in to these things. 😃

**Comment by tchayen** [comment]
Closing as nothing happened for the past months here.
