### ISSUE TITLE
Add Folder To Workspace links

### ISSUE THREAD

**Issue by geekscrapy** [tchayen/markdown-links#43]
I've just started using Foam, and links work fine (and are shown) if the .md resides in the workspace directory, however I need to add other directories using the "Add Folder to workspace" command. When I do this and add a reference a link between a .md in the original workspace and one in the newly added workspace it isn't shown in the graph

**Comment by ianjsikes** [comment]
I believe this is fixed by #35 which was just merged.

**Comment by tchayen** [comment]
Thanks for pointing it out @ianjsikes. Closing the issue. If it does not help @geekscrapy please let me know.

**Comment by geekscrapy** [comment]
Yup, works great now 👍

**Comment by tchayen** [comment]
Glad to hear that 🎉 .
