### ISSUE TITLE
[Idea] Another view like mindmap editor

### ISSUE THREAD

**Issue by Krysl** [tchayen/markdown-links#44]
On existing plugin, I always need to click on the node to switch to a different editor to view/edit the content of the file. 
It would be convenient if I could see the details of all files in only one view.

So，I need a graph like a mindmap editor:
- Show other parts of markdown (not just `# H1` heading)，such as：
  - Headers: `## H2`, `### H3`, ...
  - Text (**Bold**, *Italic*, ...)
  - Ordered Lists
  - Unordered Lists
  - Images
  - Links (Markdown, wiki, ...)
  - `Code`
  - ...
- Can globally control the level of display
- Collapse/Expand a node's subitem by hand
- hover on a node will show the content
- focus mode
  When the node of a file is selected(using `ctrl+click` or `Double-click`), 
  it will re-layout to make it in the center and can hide/show unrelated nodes
- edit content
  Edit content directly in the graph maybe difficult，use VSCode's editor temporarily

**Comment by tchayen** [comment]
I really love those ideas but unfortunately it is absolutely out of scope of this extension and probably any kind of a vscode extension – it is a good candidate for a product on its own.

Thanks for bringing it here but unfortunately I can't help with implementing it here.

**Comment by Krysl** [comment]
@tchayen 
Well, I am trying to write this plugin by myself since last week. 
Unfortunately, I haven't studied front-end development before, so the completion time is far away.
