### ISSUE TITLE
Link to a section in a another file

### ISSUE THREAD

**Issue by geekscrapy** [tchayen/markdown-links#47]
It would be great to link to a particular section within another md file! This way you can be very precise about the link and makes navigating a lot better

**Comment by asbjornb** [comment]
Linking to a section works well but just doesn't show in the graph right? I do something like this all the time:
`See more at [Concepts:Executions](concepts.md##executions)`
I don't have support on windows for markdown links in the graph yet so not sure if it will show in the graph.

**Comment by geekscrapy** [comment]
Thanks, I didn't think about the URL type # to link to sections! I'll try it out.
FYI I'm on macos

**Comment by tchayen** [comment]
Hm, I would have to check it but for I believe that for now anything that is not discovered to be a real local file is treated as an external link and then ignored. So why not having it properly recognized.

**Comment by geekscrapy** [comment]
Also links to #60 , from what @tchayen said about external links being ignored

**Comment by nixsee** [comment]
I'm curious, given that section links are possible, how does the graph treat them - do they just link to the linked section's file or are they not linked at all?

**Comment by tchayen** [comment]
Does obsidian have section linking?

**Comment by vanadium23** [comment]
Yes, but very strange: https://publish.obsidian.md/help/How+to/Link+to+blocks

**Comment by tchayen** [comment]
Just realized that linking to sections is not really a thing that we want (at least as far as I understand) to show on the graph so it is out of scope of the extension, right?

Closing for now, but feel free to comment if I am wrong here.
