### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by tchayen** [tchayen/markdown-links#5]
The extension is in desperate need of automated testing. I will soon start implementing them.

Some ideas that come to my mind:
- how given side effect (addition of a file, removal of a file, alteration of a link, alteration of a title) influences rendered graph,
- what entries to `nodes` and `edges` arrays are caused by parsing of given file,
- Mini integration tests: what graph is generated by given directory.
- Snapshot tests: what SVG is generated by given graph.

**Comment by MahbubAlam231** [comment]
@tchayen just wanted to ask how to install your program?

**Comment by tchayen** [comment]
Closing as there is no point in keeping it open for that long with no progress.
