### ISSUE TITLE
Feature request: Custom working directory

### ISSUE THREAD

**Issue by sutram** [tchayen/markdown-links#55]
Hello,

This is a great project and helps me visualize the links between various Markdown files in a directory. I've recently been using a different extension called Notes that allows me to look at my Markdown notes without switching workspaces by creating and displaying a separate "Notes" directory. This means that I could be coding using a workspace while also adding Markdown content in that directory.

Markdown Links just seems to use the current working directory of the current workspace. Is it possible to add an option to change the working directory so that Markdown notes can be visualized in this directory?

Thank you!

**Comment by tchayen** [comment]
How would you see that?

One solution that comes to my mind is a separate command `Markdown Links: Show Graph (in the file's directory)` that would open as the name suggests instead of CWD.

**Comment by sutram** [comment]
@tchayen The Notes extension just displays the contents of a different directory in a workspace. You can then work with files in that directory while also working on files in the current workspace. My request is to have Markdown Links be able to operate only on files in this different directory instead of the directory in the current workspace. The github project for the extension: https://github.com/dionmunk/vscode-notes. Here is a screenshot of that extension in action:

<img width="1392" alt="Screen Shot 2020-08-25 at 12 50 13 PM" src="https://user-images.githubusercontent.com/8870300/91215460-c53ec500-e6d1-11ea-97ce-74752ee45670.png">

Thanks

**Comment by tchayen** [comment]
Ok, so after re-reading through your suggestion I think that what I mentioned before would be the best way to achieve that in context of how Markdown Links works. Adding a vscode tab like notes extension does is not an option; it wouldn't be possible to put a webview with a graph there.

I like the idea and will definitely consider it, but currently I won't have much time so I won't be the one implementing it any time soon. If anyone finds it useful – feel free to ask me, I will be glad to help implementing that.

Thanks again for the idea and clarification! If you think I didn't get your idea right – please correct me.
