### ISSUE TITLE
Scale Node Title with size.

### ISSUE THREAD

**Issue by Am3ra** [tchayen/markdown-links#57]
https://github.com/tchayen/markdown-links/blob/045dd4fc9c0013da0c69198a7d7f3e645e7c1d18/static/graphs/obsidian/graph.js#L258

I think it would be good to scale the size of the node in relation to the size, to give it more importance. Maybe set the scaling factor as an option?

**Comment by tchayen** [comment]
I don't think making it an option would be a good idea. There are custom graph views, now we would be adding configuration to them. I think it would better to hear more opinions hear and decide whether or not we should alter the current styling.

@dobrovolsky What do you think about it?

**Comment by dobrovolsky** [comment]
> I don't think making it an option would be a good idea. There are custom graph views, now we would be adding configuration to them.
I agree with you.
Imagine a situation when there will be 10s different graphs with different options. It will create lots of mess.
But on the other hand, we could create one settings option with a JSON object and specify what we want to change in our graph.

**Comment by Am3ra** [comment]
I also agree that making it a user-defined option probably isn't good. 

Either way, I still think it would be interesting to scale the labels, even if you can't choose the scale, the same way that the nodes are scaled and can't be changed. 

Implementing this change is relatively simple

**Comment by ingalless** [comment]
@tchayen @dobrovolsky @Am3ra perhaps, at the very least, we could get the user's configured font size and base the scaling off of that? The option is `editor.fontSize` for reference.

**Comment by tchayen** [comment]
@ingalless that sounds much better (and accessible too). We should connect font size to the font size of the editor I guess, and in case of obsidian make scaling based also on that base value.

**Comment by Am3ra** [comment]
@ingalless  Regarding the obsidian version, I think `${ nodeSize[d.id] * editor.fontSize / 8}px` would be a good way to scale it. 

nodeSize is a value between 8 and 24, so dividing by 8 would scale to a value between 1 and 3. 

Multiplying by the base fontSize I think would achieve a good scaling range. I'm testing that out now. Any thoughts?

**Comment by ingalless** [comment]
@Am3ra feel free to open a PR for the change! I'm not actually too familiar with graph generation code, so I can't comment on your method. Just so long as it is easily understandable (either through a comment or extracting it into a function) then I'm fine with it!

@tchayen will probably be able to add some more comprehensive thoughts 😆

**Comment by Am3ra** [comment]
Created the PR, wasn't able to link it to this issue 😢 . However, it very simply changed the behaviour of the graph labels.

![Screen Shot 2020-09-19 at 17 23 54](https://user-images.githubusercontent.com/17537489/93690589-abf62200-fa9f-11ea-925d-9314dbaf865f.png)

In this image, it's pretty clear to see the difference in label sizes corresponding to node size.

**Comment by Am3ra** [comment]
Closed by #62
