### ISSUE TITLE
Support [[[...]]] links

### ISSUE THREAD

**Issue by srid** [tchayen/markdown-links#59]
Triple square bracket links represent "folgezettel" links. It is supported by Neuron: https://neuron.zettel.page/2011504.html

Some vscode extensions, like https://github.com/svsool/vscode-memo#memo, have no problem supporting both variations. However, this extension works only with `[[..]]`. It entirely ignores `[[[..]]]` links.

If this little feature gets added, then neuron users would be able to use this great extension!

**Comment by tchayen** [comment]
Thanks for the feedback! I wasn't aware of that. I am adding it to the list in #28. If there's anything else you would want to add or clarify, let's move the discussion there so others can better see it in context of other planned changes to the linking system.
