### ISSUE TITLE
Long titles should be cut or wrapped

### ISSUE THREAD

**Issue by jmg-duarte** [tchayen/markdown-links#66]
Hello everyone,

I'm using markdown-links as a part of foam to organize my thesis work.

When writing summaries of articles, if I use the article title it becomes difficult to read the graph. I could use something else but organization wise it will just lead to entropy.
I currently have only one node like it but it is easy to see it won't scale.

![image](https://user-images.githubusercontent.com/15343819/96104242-80b0f800-0ed0-11eb-835e-3072277d8728.png)

My suggestion, to keep the parser simple (using the first, single # sign as title) is to allow cutting or wrapping the title.
I believe this to be a simple change and I do not mind implementing it.

https://github.com/tchayen/markdown-links/blob/50dd76bde7b004b3cae162346f1da0f5b52f7753/src/parsing.ts#L41

In the line above, we can just add `substring(0, limit).concat("...")` where limit is defined by the user. In the case that `title != null` of course.

**Comment by ingalless** [comment]
@jmg-duarte Well raised, seems a good issue to investigate.
Would you be happy to make the changes and attach a screenshot in a PR? The change you've suggested seems to make sense.

**Comment by jmg-duarte** [comment]
I will try it out then! Will report back ASAP

A quinta, 15 de out de 2020, 11:37, ingalless <notifications@github.com>
escreveu:

**Comment by jmg-duarte** [comment]
I have the results.
For the *default* graph kind:
![image](https://user-images.githubusercontent.com/15343819/96132287-23c63980-0ef2-11eb-8853-c3e59e7c484c.png)

For the *obsidian* graph kind:
![image](https://user-images.githubusercontent.com/15343819/96132221-0db87900-0ef2-11eb-935c-2be86f9f91e3.png)

I quickly fixed the number to 16 but it is just a matter of adding a setting and testing.

I'll do it and submit a PR

**Comment by jmg-duarte** [comment]
Closing this issue as it is being handled by #67

**Comment by tchayen** [comment]
Thanks for reporting this!
