### ISSUE TITLE
[Feature Request] Option to search for references when renaming a file

### ISSUE THREAD

**Issue by RobMandelings** [tchayen/markdown-links#77]
Currently, when renaming a file, it only changes the filename itself. All the markdown links that refer to this file become invalidated, as it doesn't link to that file anymore. It would be very helpful to have a search for all markdown links referencing to this file to also change accordingly.

**Comment by tchayen** [comment]
I am afraid this is out of scope for this extension. We are only concerned about visualising the graph. Any changes to actual files are handled by various other vscode extensions.
